import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI")
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME")
COLLECTION_NAME = os.getenv("COLLECTION_NAME")

N_CLUSTERS = 3
RANDOM_STATE = 42

LOW_INCOME_THRESHOLD = 10000
MEDIUM_INCOME_THRESHOLD = 50000
HOSPITAL_DISTANCE_THRESHOLD = 10
LARGE_FAMILY_SIZE_THRESHOLD = 5

HIGH_URGENCY_MIN = 70    
MODERATE_URGENCY_MIN = 40

MIN_SAMPLES_FOR_ML = 10  
SYNTHETIC_DATA_RATIO = 5  
ML_TEST_SPLIT = 0.2
ML_CROSS_VAL_FOLDS = 5

RULE_BASED_WEIGHT = 0.6  
ML_WEIGHT = 0.4         

OUTPUT_DIR = "outputs"
DENDROGRAM_PATH = f'{OUTPUT_DIR}/dendrogram.png'
PCA_SCATTER_PLOT_PATH = f'{OUTPUT_DIR}/pca_scatter_plot.png'
PCA_CLUSTER_PLOT_PATH = f'{OUTPUT_DIR}/pca_cluster_plot.png'
FEATURE_IMPORTANCE_PATH = f'{OUTPUT_DIR}/feature_importance.png'

MODEL_DIR = "models"
ML_MODEL_PATH = f'{MODEL_DIR}/urgency_classifier.pkl'